name: 'yq - portable yaml processor'
description: 'create, read, update, delete, merge, validate and do more with yaml'
branding:
  icon: command
  color: gray-dark
inputs:
  cmd:
    description: 'The Command which should be run'
    required: true
outputs:
  result:
    description: "The complete result from the yq command being run"
runs:
  using: 'docker'
  image: 'docker://mikefarah/yq@sha256:a437fd0d73b1ff88beb9687a1913ff0963ed2efd38759e8f73c2bfb8e31d7708' # 4-githubaction
  args:
    - ${{ inputs.cmd }}
