name: Test Yq Action
on: 
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Get test
        id: get_value
        uses: mikefarah/yq@c14f446382944492701b16c1ddb48bb9dbe683e3 # master
        with:
          cmd: yq '.test' examples/multiline-text.yaml
      - name: Multiline test
        env:
          RESULT: ${{ steps.get_value.outputs.result }}
        run: echo "### It was [$RESULT]" >> $GITHUB_STEP_SUMMARY
      - name: Write inplace test
        id: lookupSdkVersion
        uses: mikefarah/yq@c14f446382944492701b16c1ddb48bb9dbe683e3 # master
        with:
          cmd: yq -i '.b.c = 5' examples/sample.yaml